/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerBook;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author SYIFA MAULIDA
 */
public class FormBook extends javax.swing.JFrame {

    /**
     * Creates new form FormBuku
     */
    public FormBook() {
        initComponents();
        controllerBook = new ControllerBook(this);
        controllerBook.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListBook = new javax.swing.JTable();
        jButtonDeleteBook1 = new javax.swing.JButton();
        jButtonUpdateBook2 = new javax.swing.JButton();
        jButtonIssueBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Books");

        jButtonAddBook.setBackground(new java.awt.Color(0, 80, 179));
        jButtonAddBook.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButtonAddBook.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddBook.setText("Add New Book");
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });

        jTableListBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableListBook);

        jButtonDeleteBook1.setBackground(new java.awt.Color(204, 0, 0));
        jButtonDeleteBook1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButtonDeleteBook1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteBook1.setText("Delete Book");
        jButtonDeleteBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteBook1ActionPerformed(evt);
            }
        });

        jButtonUpdateBook2.setBackground(new java.awt.Color(0, 204, 153));
        jButtonUpdateBook2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButtonUpdateBook2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdateBook2.setText("Update Book");
        jButtonUpdateBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateBook2ActionPerformed(evt);
            }
        });

        jButtonIssueBook.setBackground(new java.awt.Color(255, 204, 102));
        jButtonIssueBook.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButtonIssueBook.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIssueBook.setText("Issue Book");
        jButtonIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIssueBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteBook1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUpdateBook2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIssueBook)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddBook)
                        .addComponent(jButtonDeleteBook1)
                        .addComponent(jButtonUpdateBook2)
                        .addComponent(jButtonIssueBook)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed
        // TODO add your handling code here:
        FormCreateBook fcb = new FormCreateBook();
        fcb.show();
        
        dispose();
    }//GEN-LAST:event_jButtonAddBookActionPerformed

    private void jButtonDeleteBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteBook1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTableListBook.getSelectedRow();
    
    if (selectedRowIndex != -1) {
        int bookId = (int) jTableListBook.getValueAt(selectedRowIndex, 0); // Assuming ID is in the first column
        
        // Instantiate ControllerBook
        ControllerBook controllerBook = new ControllerBook(this); // 'this' refers to the current form

        // Call delete method in ControllerBook
        controllerBook.deleteBook();
        
        // Optionally, refresh the table or update the GUI after deletion
        controllerBook.isiTable(); // Assuming this method updates the table in the GUI
    } else {
        JOptionPane.showMessageDialog(null, "Please select a book to delete");
    }
    }//GEN-LAST:event_jButtonDeleteBook1ActionPerformed

    private void jButtonUpdateBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateBook2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTableListBook.getSelectedRow();
        
        if(selectedRowIndex != -1) {
            int bookId = (int) jTableListBook.getValueAt(selectedRowIndex, 0);
            
            ControllerBook controllerBook = new ControllerBook(this);
            
            controllerBook.isiTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a book to update");
        }
    }//GEN-LAST:event_jButtonUpdateBook2ActionPerformed

    private void jButtonIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIssueBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIssueBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JButton jButtonDeleteBook1;
    private javax.swing.JButton jButtonIssueBook;
    private javax.swing.JButton jButtonUpdateBook2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListBook;
    // End of variables declaration//GEN-END:variables

    ControllerBook controllerBook;
    
    public JTable getTabelData() {
        return jTableListBook;
    }
}
